BUG: Fix data location in non solution introduction notebook
Fix data location in non solution introduction notebook.

Fixes:
```
(...)
----> 8 layout = BIDSLayout("../../../data/ds000221", validate=False)
(...)
     67     if not os.path.exists(root):
---> 68         raise ValueError("BIDS root does not exist: %s" % root)
(...)
ValueError: BIDS root does not exist: /home/runner/work/SDC-BIDS-dMRI/data/ds000221
```

reported in:
=/=carpentries-incubator/=/=SDC-BIDS-dMRI/runs/3120044369?check_suite_focus=true#step:7:72