BUG: Fix data paths in preprocessing episode solutions notebook
Fix data paths in preprocessing episode solutions notebook.

Fixes:
```
=================================== FAILURES ===================================
______ code/preprocessing/solutions/preprocessing_solutions.ipynb::Cell 3 ______
Notebook cell execution failed
Cell 3: Cell execution caused an exception

CalledProcessError: Command 'b'\n
mkdir -p
../../../data/ds000221/derivatives/uncorrected_topup/sub-010006/ses-01/dwi/work\n\n
fslmerge -t
../../../data/ds000221/derivatives/uncorrected_topup/sub-010006/ses-01/dwi/work/sub-010006_ses-01_acq-SEfmapDWI_epi.nii.gz
../../data/ds000221/sub-010006/ses-01/fmap/sub-010006_ses-01_acq-SEfmapDWI_dir-AP_epi.nii.gz
../../data/ds000221/sub-010006/ses-01/fmap/sub-010006_ses-01_acq-SEfmapDWI_dir-PA_epi.nii.gz\n''
 returned non-zero exit status 134.
```

reported in:
=/=carpentries-incubator/=/=SDC-BIDS-dMRI/runs/3253339903?check_suite_focus=true#step:13:78